-- MySQL Script generated by MySQL Workbench
-- Fri Oct  1 11:50:55 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema zil3-zgarciach
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema zil3-zgarciach
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `zil3-zgarciach` DEFAULT CHARACTER SET utf8 ;
USE `zil3-zgarciach` ;

-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Site_UNIV`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Site_UNIV` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Site_UNIV` (
  `idSite` INT NOT NULL,
  `nomSite` VARCHAR(100) NULL,
  PRIMARY KEY (`idSite`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`UFR`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`UFR` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`UFR` (
  `idUFR` INT NOT NULL,
  `nomUFR` VARCHAR(100) NULL,
  `nomUFR_Court` INT NULL,
  PRIMARY KEY (`idUFR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Departement`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Departement` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Departement` (
  `idDepartement` INT NOT NULL,
  `nomDepartement` VARCHAR(100) NULL,
  `nomDepartement_Court` INT NULL,
  `UFR_idUFR` INT NOT NULL,
  PRIMARY KEY (`idDepartement`),
  INDEX `fk_Departement_UFR1_idx` (`UFR_idUFR` ASC),
  CONSTRAINT `fk_Departement_UFR1`
    FOREIGN KEY (`UFR_idUFR`)
    REFERENCES `zil3-zgarciach`.`UFR` (`idUFR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Parcours`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Parcours` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Parcours` (
  `idParcours` INT NOT NULL,
  `nomParcours` VARCHAR(100) NULL,
  PRIMARY KEY (`idParcours`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Formation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Formation` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Formation` (
  `idFormation` INT NOT NULL,
  `type` VARCHAR(10) NULL,
  `niveau` VARCHAR(10) NULL,
  `Parcours_idParcours` INT NOT NULL,
  `Departement_idDepartement` INT NOT NULL,
  PRIMARY KEY (`idFormation`),
  INDEX `fk_Formation_Parcours1_idx` (`Parcours_idParcours` ASC),
  INDEX `fk_Formation_Departement1_idx` (`Departement_idDepartement` ASC),
  CONSTRAINT `fk_Formation_Parcours1`
    FOREIGN KEY (`Parcours_idParcours`)
    REFERENCES `zil3-zgarciach`.`Parcours` (`idParcours`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Formation_Departement1`
    FOREIGN KEY (`Departement_idDepartement`)
    REFERENCES `zil3-zgarciach`.`Departement` (`idDepartement`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Demographie`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Demographie` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Demographie` (
  `idDemographie` INT NOT NULL,
  `ageDemographie` INT NULL,
  `anneeDemographie` INT NULL,
  `nbPersonnes` INT NULL,
  PRIMARY KEY (`idDemographie`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Effectif`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Effectif` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Effectif` (
  `anneeRef` INT NOT NULL,
  `effectif` INT NULL,
  `Demographie_idDemographie` INT NOT NULL,
  `Formation_idFormation` INT NOT NULL,
  PRIMARY KEY (`anneeRef`, `Formation_idFormation`),
  INDEX `fk_Effectif_Demographie1_idx` (`Demographie_idDemographie` ASC),
  INDEX `fk_Effectif_Formation1_idx` (`Formation_idFormation` ASC),
  CONSTRAINT `fk_Effectif_Demographie1`
    FOREIGN KEY (`Demographie_idDemographie`)
    REFERENCES `zil3-zgarciach`.`Demographie` (`idDemographie`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Effectif_Formation1`
    FOREIGN KEY (`Formation_idFormation`)
    REFERENCES `zil3-zgarciach`.`Formation` (`idFormation`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `zil3-zgarciach`.`Situation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `zil3-zgarciach`.`Situation` ;

CREATE TABLE IF NOT EXISTS `zil3-zgarciach`.`Situation` (
  `Site_UNIV_idSite` INT NOT NULL,
  `UFR_idUFR` INT NOT NULL,
  PRIMARY KEY (`Site_UNIV_idSite`, `UFR_idUFR`),
  INDEX `fk_Site_UNIV_has_UFR_UFR1_idx` (`UFR_idUFR` ASC),
  INDEX `fk_Site_UNIV_has_UFR_Site_UNIV_idx` (`Site_UNIV_idSite` ASC),
  CONSTRAINT `fk_Site_UNIV_has_UFR_Site_UNIV`
    FOREIGN KEY (`Site_UNIV_idSite`)
    REFERENCES `zil3-zgarciach`.`Site_UNIV` (`idSite`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Site_UNIV_has_UFR_UFR1`
    FOREIGN KEY (`UFR_idUFR`)
    REFERENCES `zil3-zgarciach`.`UFR` (`idUFR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
